---
abstract: 'Reserved SQL words by ANSI/ISO'
author:
  - 'Christian Hansen C<chansen@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SQL-ReservedWords
provides:
  SQL::ReservedWords:
    file: lib/SQL/ReservedWords.pm
    version: 0.8
  SQL::ReservedWords::DB2:
    file: lib/SQL/ReservedWords/DB2.pm
    version: 0.8
  SQL::ReservedWords::MySQL:
    file: lib/SQL/ReservedWords/MySQL.pm
    version: 0.8
  SQL::ReservedWords::ODBC:
    file: lib/SQL/ReservedWords/ODBC.pm
    version: 0.8
  SQL::ReservedWords::Oracle:
    file: lib/SQL/ReservedWords/Oracle.pm
    version: 0.8
  SQL::ReservedWords::PostgreSQL:
    file: lib/SQL/ReservedWords/PostgreSQL.pm
    version: 0.8
  SQL::ReservedWords::SQLServer:
    file: lib/SQL/ReservedWords/SQLServer.pm
    version: 0.8
  SQL::ReservedWords::SQLite:
    file: lib/SQL/ReservedWords/SQLite.pm
    version: 0.8
  SQL::ReservedWords::Sybase:
    file: lib/SQL/ReservedWords/Sybase.pm
    version: 0.8
requires:
  Sub::Exporter: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.8
